services:
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm start"
    depends_on:
      - backend

  backend:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5500:5500"
    command: >
      sh -c "npm install && npm run dev"

volumes:
  data:
